paths:
  uploads: public/uploads
  static: public
collections_config:
  data:
    path: src/data
    icon: data_usage
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    icon: wysiwyg
    url: '[full_slug]'
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Brussels
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
